name: workflow

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: start message
        run: echo "Starting workflow"
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.8'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CNNCifar10Mock.py
        run: |
          python CNNCifar10Mock.py

      - name: check for changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --staged --quiet || echo "changes = true" >> $GITHUB_ENV

      - name: commit and push if changes
        if: env.changes == 'true'
        run: |
          git commit -m "update data hyperparameters"
          git push

      - name: debug
        run: |
          echo "Checking contents of the directory"
          ls -R data
   

      - name: Save generated plot
        uses: actions/upload-artifact@v3
        with:
          name: generated-plot
          path: data/plots/training_plots.png

      - name: Save model
        uses: actions/upload-artifact@v3
        with:
          name: model
          path: data/model/cnn_cifar10.h5
